### ISSUE TITLE
java.sql.SQLException: Illegal Type  & sqlline

### ISSUE THREAD

**Issue by matteoredaelli** [elbosso/openldap-jdbcldap#3]
Hello

using jdbcldap with sqlline I get

```
0: jdbc:ldap://dmc001.group.redaelli.com/> !set verbose true
0: jdbc:ldap://dmc001.group.redaelli.com/> select * from DC=group,DC=redaelli,DC=com where sn='Redaelli';
Sort by : null
Error: Illegal Type (state=,code=0)
java.sql.SQLException: Illegal Type
        at com.octetstring.jdbcLdap.sql.JdbcLdapMetaData.getColumnTypeName(JdbcLdapMetaData.java:88)
        at sqlline.Rows$Row.<init>(Rows.java:229)
        at sqlline.BufferedRows.<init>(BufferedRows.java:53)
        at sqlline.SqlLine.print(SqlLine.java:1770)
        at sqlline.Commands.executeSingleQuery(Commands.java:1139)
        at sqlline.Commands.execute(Commands.java:1079)
        at sqlline.Commands.sql(Commands.java:1033)
        at sqlline.SqlLine.dispatch(SqlLine.java:822)
        at sqlline.SqlLine.begin(SqlLine.java:596)
        at sqlline.SqlLine.start(SqlLine.java:269)
        at sqlline.SqlLine.main(SqlLine.java:208)
```

For details, please look at the issue

  https://github.com/julianhyde/sqlline/issues/450

Regards
Matteo

**Comment by elbosso** [comment]
Hi, 

yes, what is mentioned in https://github.com/julianhyde/sqlline/issues/450 is completely correct. I caon only repeat what I stated earlier - i did start by mending the obvious flaws resulting in NPEs and did not do a rigorous testing for all aspects ofg the API. So I would like to thank all of you again and again who help to improve this by using it and giving me feedback.
Now - back to matters at hand: I copied a Mapping class from one of my other JDBC Drivers and used it instead of the original code - now the "Illegal Type" code should vanish for everyday use and on the whole it should be seen much less freqently
